// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Migration.Core.Template.Bjsc
{
    using System.Linq;
    using System.Text;
    using Migration.Model;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class BjscTemplate : BjscTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 7 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"

    if(this.WithInclude)
    {

            
            #line default
            #line hidden
            this.Write("include \'BaijiCommonTypes.bjsc\'\r\ninclude \'BaijiMobileCommonTypes.bjsc\'\r\n\r\n");
            
            #line 14 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"

    }

            
            #line default
            #line hidden
            
            #line 17 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"

    if(this.Root != null)
    {
            switch (this.Root.NodeType)
            {
                case Migration.Model.NodeType.Class:
                    {
                        var classNode = this.Root as ClassNode;
                        if(classNode != null)
                        {
                            if(!string.IsNullOrEmpty(classNode.Summary))
                            {

            
            #line default
            #line hidden
            this.Write("/* ");
            
            #line 30 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classNode.Summary));
            
            #line default
            #line hidden
            this.Write(" */\r\n");
            
            #line 31 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"

                            }

            
            #line default
            #line hidden
            this.Write("class ");
            
            #line 34 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root.Name));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 36 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"

                            if (classNode.Items != null && classNode.Items.Count > 0)
                            {
                                var propertyNodes = classNode.Items.Where(v => v.NodeType == Migration.Model.NodeType.Property).ToList();
                                foreach (var propertyNode in propertyNodes)
                                {
                                    if(propertyNode.IsChecked)
                                    {
                                        var bjscTemplate = new BjscTemplate();
                                        bjscTemplate.Root = propertyNode;
                                        var content = bjscTemplate.TransformText();

            
            #line default
            #line hidden
            
            #line 47 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(content));
            
            #line default
            #line hidden
            
            #line 47 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"

                                    }
                                }
                            }

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 53 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"

                        }
                    }

                    break;
                case Migration.Model.NodeType.None:
                    break;
                case Migration.Model.NodeType.Enum:
                    break;
                case Migration.Model.NodeType.Property:
                    {
                        var propertyNode = this.Root as PropertyNode;
                        if(propertyNode != null)
                        {
                            if(!string.IsNullOrEmpty(propertyNode.Summary))
                            {

            
            #line default
            #line hidden
            this.Write("    /* ");
            
            #line 70 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyNode.Summary));
            
            #line default
            #line hidden
            this.Write(" */\r\n");
            
            #line 71 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"

                            }

            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 74 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyNode.BjscTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 74 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyNode.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 75 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"

                        }
                    }

                    break;
                case Migration.Model.NodeType.Field:
                    break;
                case Migration.Model.NodeType.Method:
                    break;
                case Migration.Model.NodeType.Namespace:
                    {

            
            #line default
            #line hidden
            this.Write("namespace java \'");
            
            #line 87 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root.Name??string.Empty));
            
            #line default
            #line hidden
            this.Write("\'\r\nnamespace csharp \'");
            
            #line 88 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root.Name??string.Empty));
            
            #line default
            #line hidden
            this.Write("\'\r\n");
            
            #line 89 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"

                        if(this.Root.Items != null && this.Root.Items.Count > 0)
                        {
                            foreach(var item in this.Root.Items)
                            {
                                if(item.IsChecked)
                                {
                                    var bjscTemplate = new BjscTemplate();
                                    bjscTemplate.Root = item;
                                    var content = bjscTemplate.TransformText();

            
            #line default
            #line hidden
            
            #line 99 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(content));
            
            #line default
            #line hidden
            
            #line 99 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"

                                }
                            }
                        }
                    }

                    break;
                case Migration.Model.NodeType.Root:
                    {
                        if(this.Root.Items != null && this.Root.Items.Count > 0)
                        {
                            foreach(var item in this.Root.Items)
                            {
                                if(item.IsChecked)
                                {
                                    var bjscTemplate = new BjscTemplate();
                                    bjscTemplate.Root = item;
                                    var content = bjscTemplate.TransformText();

            
            #line default
            #line hidden
            
            #line 117 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(content));
            
            #line default
            #line hidden
            
            #line 117 "D:\CodingWorkspace\Migration\Migration\Core\Template\Bjsc\BjscTemplate.tt"

                                }
                            }
                        }
                    }

                    break;
                default:
                    break;
            }
    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class BjscTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
